# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_channel_data.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'custom_channel_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ustom_channel_data.proto\x12\rtaprootassets\"X\n\x0c\x41ssetGenesis\x12\x15\n\rgenesis_point\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tmeta_hash\x18\x03 \x01(\x0c\x12\x10\n\x08\x61sset_id\x18\x04 \x01(\x0c\"\x8d\x01\n\tAssetUtxo\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x32\n\rasset_genesis\x18\x02 \x01(\x0b\x32\x1b.taprootassets.AssetGenesis\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x12\n\nscript_key\x18\x04 \x01(\x0c\x12\x17\n\x0f\x64\x65\x63imal_display\x18\x05 \x01(\x05\"v\n\x05\x41sset\x12,\n\nasset_utxo\x18\x01 \x01(\x0b\x32\x18.taprootassets.AssetUtxo\x12\x10\n\x08\x63\x61pacity\x18\x02 \x01(\x03\x12\x15\n\rlocal_balance\x18\x03 \x01(\x03\x12\x16\n\x0eremote_balance\x18\x04 \x01(\x03\"9\n\x11\x43ustomChannelData\x12$\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\x14.taprootassets.Assetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_channel_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSETGENESIS']._serialized_start=44
  _globals['_ASSETGENESIS']._serialized_end=132
  _globals['_ASSETUTXO']._serialized_start=135
  _globals['_ASSETUTXO']._serialized_end=276
  _globals['_ASSET']._serialized_start=278
  _globals['_ASSET']._serialized_end=396
  _globals['_CUSTOMCHANNELDATA']._serialized_start=398
  _globals['_CUSTOMCHANNELDATA']._serialized_end=455
# @@protoc_insertion_point(module_scope)
